name: Code Quality Check

on:
  pull_request:
    branches:
      - main
      - release/v*

jobs:
  check_code:
    runs-on: ubuntu-20.04
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install packages
        run: npm ci
      - name: Run linting
        run: npm run lint
      - name: Check formatting
        run: npm run format
      - name: Run tests
        run: npm run test
